# Generated by Django 3.1.3 on 2021-01-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnrest', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
