# Generated by Django 3.1.3 on 2021-02-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnrest', '0005_jobapplication_jobpositions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
